apiVersion: v1
kind: Service
metadata:
  name: vikro-nginx1
  labels:
    app: vikro-nginx1
spec:
  type: LoadBalancer
  selector:
    app: vikro-nginx1
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80