apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo1
  name: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        build_number: ${BUILD_NUMBER}
        role: rolling-update
        app: demo1
    spec:
      containers:
      - image: vikro2021/demo1:latest
        name: demo1
        ports:
        - containerPort: 80
          name: demo1
---
apiVersion: v1
kind: Service
metadata:
  name: demo1-lb
  labels:
    app: demo1-lb
spec:
  type: LoadBalancer
  selector:
    app: demo1
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80